# Generated by Django 3.2 on 2021-05-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_auto_20210506_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
