# Generated by Django 3.2 on 2021-05-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_remove_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
