# Generated by Django 3.2 on 2021-05-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_auto_20210506_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='F_name',
        ),
    ]
