# Generated by Django 3.2 on 2021-05-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_rename_name_contact_f_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='L_name',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
